#!/usr/bin/env python3

# pylint: disable=all

import os
import sys
import argparse

import vdf

argument_parser = argparse.ArgumentParser()

argument_parser.add_argument("--csgo_path", type=str,
                             help="Path to CSGO installation.")

args = argument_parser.parse_args()

WORKING_DIR = os.path.realpath(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../"))

SOURCEMOD_LANGUAGES = {
    "en": "english",
    "bg": "bulgarian",
    "chi": "schinese",
    "cze": "czech",
    "da": "danish",
    "de": "german",
    "el": "greek",
    "es": "spanish",
    "fi": "finnish",
    "fr": "french",
    "hu": "hungarian",
    "it": "italian",
    "jp": "japanese",
    "ko": "korean",
    "las": "latam",
    "nl": "dutch",
    "no": "norwegian",
    "pl": "polish",
    "pt": "brazilian",
    "pt_p": "portuguese",
    "ro": "romanian",
    "ru": "russian",
    "sv": "swedish",
    "th": "thai",
    "tr": "turkish",
    "ua": "ukrainian",
    "vi": "vietnamese",
    "zho": "tchinese"
}

csgo_path = args.csgo_path
if not csgo_path:
    match sys.platform:
        case "win32":
            csgo_path = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\csgo legacy"
        case "darwin":
            csgo_path = os.path.expanduser("~/Library/Application Support/Steam/steamapps/common/csgo legacy")
        case "linux":
            csgo_path = os.path.expanduser("~/.local/share/Steam/steamapps/common/csgo legacy")
        case _:
            raise RuntimeError("Invalid OS")

with open(os.path.join(csgo_path, "csgo/scripts/items/items_game.txt"), encoding="utf-8") as f:
    item_schema = vdf.load(f)

music_definitions = item_schema.get("items_game").get("music_definitions")

with open(os.path.join(WORKING_DIR, "scripting", "csgo_music_kit_mapping.sp"), "w", encoding="utf-8", newline="\n") as sm_mapping:
    sm_mapping.write("// Generated by get_music_id.py, do not edit\n\n")
    sm_mapping.write("void MakeMusicKitMapping(StringMap map) {\n")
    # default music kit needs special handling
    sm_mapping.write("    map.SetValue(\"valve_csgo\", 1);\n")
    for key, value in music_definitions.items():
        music_kit_name: str | None = value.get("name")
        if not music_kit_name:
            raise RuntimeError(f"Encountered empty value when getting music kit name for {key}")
        if key in {"1", "2"} or music_kit_name.startswith("valve_csgo"):
            continue
        sm_mapping.write(f"    map.SetValue(\"{music_kit_name}\", {key});\n")
    sm_mapping.write("}\n")
    sm_mapping.write("void MakeMusicKitList(ArrayList list) {\n")
    sm_mapping.write("    list.PushString(\"valve_csgo\");\n")
    for key, value in music_definitions.items():
        music_kit_name: str | None = value.get("name")
        if not music_kit_name:
            raise RuntimeError(f"Encountered empty value when getting music kit name for {key}")
        if key in {"1", "2"} or music_kit_name.startswith("valve_csgo"):
            continue
        sm_mapping.write(f"    list.PushString(\"{music_kit_name}\");\n")
    sm_mapping.write("}\n")

CSGO_MUSIC_KIT_PHRASES_NAME = "csgo-music-kit-kits.phrases.txt"

with open(os.path.join(csgo_path, "csgo", "resource", "csgo_english.txt"), encoding="utf-16-le") as translation_eng_f:
    eng_game_lang_tokens: dict = vdf.load(translation_eng_f).get("lang").get("Tokens")

for sm_lang, source_lang in SOURCEMOD_LANGUAGES.items():
    target_file_dir = os.path.join(WORKING_DIR, "translations", sm_lang if sm_lang != "en" else "")
    current_language_phrases_dict = {"Phrases": {}}
    current_language_phrases = current_language_phrases_dict.get("Phrases")
    with open(os.path.join(csgo_path, "csgo", "resource", f"csgo_{source_lang}.txt"), encoding="utf-16-le") as translation_f:
        game_translation_phrases = vdf.load(translation_f)
        game_lang_tokens: dict = game_translation_phrases.get("lang").get("Tokens")
        if not game_lang_tokens:
            raise RuntimeError(f"Tokens for {source_lang} is empty")
        for music_id, music_item in music_definitions.items():
            music_kit_name = music_item.get("name")
            if not music_kit_name:
                raise RuntimeError(f"Encountered empty value when getting music kit name for {music_id}")
            if music_id in {"1", "2"}:
                if sm_lang != "en":
                    continue
                if current_language_phrases.get("valve_csgo") is not None:
                    continue
                current_language_phrases["valve_csgo"] = {"en": "CS:GO"}
                continue
            if music_kit_name.startswith("valve_csgo"):
                continue
            music_lang_token_key: str | None = music_item.get("loc_name")
            if not music_lang_token_key:
                raise RuntimeError("Music token is missing")
            music_lang_token_key = music_lang_token_key.lstrip("#")
            music_lang_token = game_lang_tokens.get(music_lang_token_key)
            if sm_lang == "en" and not music_lang_token:
                raise RuntimeError(f"Language token missing for {music_lang_token_key}")
            if music_lang_token:
                # skip untralsted phrases
                if sm_lang == "en" or music_lang_token != eng_game_lang_tokens.get(music_lang_token_key):
                    current_language_phrases[music_kit_name] = {sm_lang: music_lang_token}
            if current_language_phrases:
                os.makedirs(target_file_dir, exist_ok=True)
                phrases_file_content = vdf.dumps(current_language_phrases_dict, pretty=True).replace("\t", "    ")
                with open(os.path.join(target_file_dir, CSGO_MUSIC_KIT_PHRASES_NAME), "w", encoding="utf-8", newline="\n") as phrases_f:
                    phrases_f.write("// Generated by get_music_id.py, do not edit\n\n")
                    phrases_f.write(phrases_file_content)
